---
# Copyright (c) 2020-2021 Jakob Meng, <jakobmeng@web.de>
# vim:set fileformat=unix tabstop=2 shiftwidth=2 expandtab:
# kate: end-of-line unix; space-indent on; indent-width 2; remove-trailing-spaces modified;

- name: Install package dependencies
  package:
    name:
    - python3
    - python3-rpi.gpio
    state: present

- name: Copy power button script
  copy:
    src: "usr/local/bin/rpi-power-button.py"
    dest: /usr/local/bin/rpi-power-button.py
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx

- name: Copy power button service
  copy:
    src: "etc/systemd/system/rpi-power-button.service"
    dest: /etc/systemd/system/rpi-power-button.service
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  notify: 'Enable and start power button service and ensure it is not masked'
